version: '3.8'

services:
  notification_service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SMTP_HOST=smtp.example.com
      - SMTP_PORT=587
      - EMAIL_USER=your_email@example.com
      - EMAIL_PASS=your_password
